### ISSUE TITLE
missing symlink in xserver-xorg-1.9-video-emgd-meego1.2

### ISSUE THREAD

**Issue by mcurrent** [EMGD-Community/intel-binaries-linux#43]
Hi,

Package version:
xserver-xorg-1.9-video-emgd-meego1.2      1.16-201601312316+emgd~rev164~ubuntu14.04.1

Upon install, the symlink emgd_dri.so -> ../emgd-meego1.2/dri/emgd_dri.so under /usr/lib/i386-linux-gnu/dri is missing, which causes Xorg to fall back to software rasterizer.

Manually creating the link fixes the problem.

Other than that, everything seems to work great (running on Linux 4.4.47, Ubuntu 14.04.5). 

Thank you!

**Comment by thopiekar** [comment]
Would be great, if you could create a PR for it. You can do it also via browser.
Just try 😃

**Comment by mcurrent** [comment]
#53
